language: python

python:
  - "3.4"

sudo: true

git:
  submodules: false

env:
  - CC=gcc CXX=g++
  - CC=clang CXX=clang++

before_install:
  # Update submodule
  - git submodule update --init --recursive

  # Update g++
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - gcc --version
  - g++ --version

  # Update cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
  - tar xf cmake-3.2.2.tar.gz
  - cd cmake-3.2.2
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j4
  - sudo make install
  - sudo ldconfig
  - cd ../..

  # Install Qt5
  - sudo add-apt-repository -y ppa:beineri/opt-qt541
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54base qt54declarative qt54location qt54webkit qt54tools qt54qbs qt54quickcontrols libsqlite3-dev
  - sudo ln -sf /opt/qt54/bin/qmake /usr/bin/qmake

  # Build SIP
  - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.8/sip-4.16.8.tar.gz
  - tar xf sip-4.16.8.tar.gz
  - cd sip-4.16.8
  - python configure.py
  - make -j4
  - sudo make install
  - cd ..

  # Build PyQt5
  - wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4.2/PyQt-gpl-5.4.2.tar.gz
  - tar xf PyQt-gpl-5.4.2.tar.gz
  - cd PyQt-gpl-5.4.2
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
  - make -j4
  - sudo make install
  - cd ..
  - export PYTHONPATH=${PYTHONPATH}:/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages

  # Install Python requirements
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

  # Install cvxopt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools pillow numpy scipy matplotlib nose dateutil pyparsing dateutil
  - conda install --yes -c dan_blanchard python-coveralls
  - sudo apt-get install -qq liblapack-dev libblas-dev
  - pip --version
  - pip install cvxopt

install:
  # Build spica
  - cmake -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake -DENABLE_AVX=OFF -DSPICA_BUILD_EXAMPLE=OFF -DSPICA_BUILD_TEST=OFF -DSPICA_BUILD_VIEWER=OFF .
  - cmake --build .
  - export PYTHONPATH=${PYTHONPATH}:`pwd`/build/bin
  - echo $PYTHONPATH

  # Build
  - python setup.py install

script:
  - nosetests --nocapture --with-coverage --cover-package=bssrdf_estimate --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

notifications:
  email:
    recepients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
