language: python

python:
  - "3.4"

sudo: true

before_install:
  # Install Qt5
  - sudo add-apt-repository -y ppa:beineri/opt-qt541
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54base qt54declarative qt54location qt54webkit qt54tools qt54qbs qt54quickcontrols libsqlite3-dev
  - sudo ln -sf /opt/qt54/bin/qmake /usr/bin/qmake

  # Build SIP
  - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.8/sip-4.16.8.tar.gz
  - tar xf sip-4.16.8.tar.gz
  - cd sip-4.16.8
  - python configure.py
  - make -j4
  - sudo make install
  - cd ..

  # Build PyQt5
  - wget http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4.2/PyQt-gpl-5.4.2.tar.gz
  - tar xf PyQt-gpl-5.4.2.tar.gz
  - cd PyQt-gpl-5.4.2
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
  - make -j4
  - sudo make install
  - cd ..
  - export PYTHONPATH=${PYTHON_PATH}:/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages

  # Install Python requirements
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools pillow numpy scipy matplotlib nose dateutil pyparsing dateutil
  - conda install --yes -c dan_blanchard python-coveralls
  - python setup.py install

script:
  - nosetests --nocapture --with-coverage --cover-package=bssrdf_estimate --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

notifications:
  email:
    recepients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
