language: python

python:
  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools pillow numpy scipy matplotlib nose dateutil pyparsing dateutil
  - conda install --yes -c dan_blanchard python-coveralls
  - python setup.py install

script:
  - nosetests --nocapture --with-coverage --cover-package=bssrdf_estimate --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

notifications:
  email:
    recepients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
